import time
import datetime
from tkinter import *
import tkinter.messagebox 
root=Tk()
root.title("Employee Payment Management System")
root.geometry('1350x650+0+0')
root.configure(background="black")
Tops=Frame(root,width=1350,height=50,bd=8,bg="black")
Tops.pack(side=TOP)
f1=Frame(root,width=600,height=600,bd=8,bg="black")
f1.pack(side=LEFT)
f2=Frame(root,width=300,height=700,bd=8,bg="black")
f2.pack(side=RIGHT)
fla=Frame(f1,width=600,height=200,bd=8,bg="black")
fla.pack(side=TOP)
flb=Frame(f1,width=300,height=600,bd=8,bg="black")
flb.pack(side=TOP)
l1=Label(Tops,font=('arial',30,'bold'),text="Employee Payment Management system \n BY SHRI SWETHA RAJ ",bd=10,fg="blue",bg="black")
l1.grid(row=0,column=0)
def exit():
  exit=tkinter.messagebox.askyesno("Employee system","Do you want to exit the system")
  if exit>0:
    root.destroy()
    return
def reset():
  Name.set("")
  Address.set("")
  HoursWorked.set("")
  wageshour.set("")
  Payable.set("")
  Taxable.set("")
  NetPayable.set("")
  GrossPayable.set("")
  OverTimeBonus.set("")
  Employer.set("")
  NINumber.set("")
  txtpayslip.delete("1.0",END)
def enterinfo():
  txtpayslip.delete("1.0",END)
  txtpayslip.insert(END,"\t\tPay Slip\n\n")
  txtpayslip.insert(END,"Name :\t\t"+Name.get()+"\n\n")
  txtpayslip.insert(END,"Address :\t\t"+Address.get()+"\n\n")
  txtpayslip.insert(END,"Designation :\t\t"+Employer.get()+"\n\n")
  txtpayslip.insert(END,"ID Number :\t\t"+NINumber.get()+"\n\n")
  txtpayslip.insert(END,"Hours Worked :\t\t"+HoursWorked.get()+"\n\n")
  txtpayslip.insert(END,"Net Pay :\t\t"+NetPayable.get()+"\n\n")
  txtpayslip.insert(END,"Wages per hour :\t\t"+wageshour.get()+"\n\n")
  txtpayslip.insert(END,"Tax Paid :\t\t"+Taxable.get()+"\n\n")
  txtpayslip.insert(END,"Payable :\t\t"+Payable.get()+"\n\n") 
def weeklywages():
  txtpayslip.delete("1.0",END)
  hoursworkedperweek=float(HoursWorked.get())
  wagesperhours=float(wageshour.get())
  paydue=wagesperhours*hoursworkedperweek
  paymentdue="INR",str('%.2f'%(paydue))
  Payable.set(paymentdue)
  tax=paydue*0.2
  taxable="INR",str('%.2f'%(tax))
  Taxable.set(taxable)
  netpay=paydue-tax
  netpays="INR",str('%.2f'%(netpay))
  NetPayable.set(netpays)
  if hoursworkedperweek > 40:
    overtimehours=(hoursworkedperweek-40)+wagesperhours*1.5
    overtime="INR",str('%.2f'%(overtimehours))
    OverTimeBonus.set(overtime)
  elif hoursworkedperweek<=40:
    overtimepay=(hoursworkedperweek-40)+wagesperhours*1.5
    overtimehrs="INR",str('%.2f'%(overtimepay))
    OverTimeBonus.set(overtimehrs)  
  return    
Name=StringVar()
Address=StringVar()
HoursWorked=StringVar()
wageshour=StringVar()
Payable=StringVar()
Taxable=StringVar()
NetPayable=StringVar()
GrossPayable=StringVar()
OverTimeBonus=StringVar()
Employer=StringVar()
NINumber=StringVar()
TimeOfOrder=StringVar()
DateOfOrder=StringVar()
DateOfOrder.set(time.strftime("%d/%m/%Y"))
l2=Label(fla,text="Name",font=('arial',16,'bold'),bd=20,fg="red",bg="black").grid(row=0,column=0)
l3=Label(fla,text="Address",font=('arial',16,'bold'),bd=20,fg="red",bg="black").grid(row=0,column=2)
l4=Label(fla,text="Designation",font=('arial',16,'bold'),bd=20,fg="red",bg="black").grid(row=1,column=0)
l5=Label(fla,text="ID Number",font=('arial',16,'bold'),bd=20,fg="red",bg="black").grid(row=1,column=2)
l6=Label(fla,text="Hours Worked",font=('arial',16,'bold'),bd=20,fg="red",bg="black").grid(row=2,column=0)
l7=Label(fla,text="Hourly Rate",font=('arial',16,'bold'),bd=20,fg="red",bg="black").grid(row=2,column=2)
l8=Label(fla,text="Tax",font=('arial',16,'bold'),bd=20,anchor='w',fg="red",bg="black").grid(row=3,column=0)
l9=Label(fla,text="OverTime",font=('arial',16,'bold'),bd=20,fg="red",bg="black").grid(row=3,column=2)
l10=Label(fla,text="GrossPay",font=('arial',16,'bold'),bd=20,fg="red",bg="black").grid(row=4,column=0)
l11=Label(fla,text="Net Pay",font=('arial',16,'bold'),bd=20,fg="red",bg="black").grid(row=4,column=2)
etxname=Entry(fla,textvariable=Name,font=('arial',16,'bold'),bd=16,width=22,justify='left')
etxname.grid(row=0,column=1)
etxaddress=Entry(fla,textvariable=Address,font=('arial',16,'bold'),bd=16,width=22,justify='left')
etxaddress.grid(row=0,column=3)
etxemployer=Entry(fla,textvariable=Employer,font=('arial',16,'bold'),bd=16,width=22,justify='left')
etxemployer.grid(row=1,column=1)
etxhoursworked=Entry(fla,textvariable=HoursWorked,font=('arial',16,'bold'),bd=16,width=22,justify='left')
etxhoursworked.grid(row=2,column=1)
etxwagesperhours=Entry(fla,textvariable=wageshour,font=('arial',16,'bold'),bd=16,width=22,justify='left')
etxwagesperhours.grid(row=2,column=3)
etxnin=Entry(fla,textvariable=NINumber,font=('arial',16,'bold'),bd=16,width=22,justify='left')
etxnin.grid(row=1,column=3)
etxgrosspay=Entry(fla,textvariable=Payable,font=('arial',16,'bold'),bd=16,width=22,justify='left')
etxgrosspay.grid(row=4,column=1)
etxnetpay=Entry(fla,textvariable=NetPayable,font=('arial',16,'bold'),bd=16,width=22,justify='left')
etxnetpay.grid(row=4,column=3)
etxtax=Entry(fla,textvariable=Taxable,font=('arial',16,'bold'),bd=16,width=22,justify='left')
etxtax.grid(row=3,column=1)
etxovertime=Entry(fla,textvariable=OverTimeBonus,font=('arial',16,'bold'),bd=16,width=22,justify='left')
etxovertime.grid(row=3,column=3)
payslip=Label(f2,textvariable=DateOfOrder,font=('arial',21,'bold'),fg="red",bg="black").grid(row=0,column=0)
txtpayslip=Text(f2,height=22,width=34,bd=16,font=('arial',13,'bold'),fg="green",bg="black")
txtpayslip.grid(row=1,column=0)
b1=Button(flb,text='Weekly Salary',padx=16,pady=16,bd=8,font=('arial',16,'bold'),width=14,fg="red",bg="black",command=weeklywages).grid(row=0,column=0)
b2=Button(flb,text='Reset',padx=16,pady=16,bd=8,font=('arial',16,'bold'),width=14,command=reset,fg="red",bg="black").grid(row=0,column=1)
b3=Button(flb,text='View Payslip',padx=16,pady=16,bd=8,font=('arial',16,'bold'),width=14,command=enterinfo,fg="red",bg="black").grid(row=0,column=2)
b4=Button(flb,text='Exit System',padx=16,pady=16,bd=8,font=('arial',16,'bold'),width=14,command=exit,fg="red",bg="black").grid(row=0,column=3)
root.mainloop()
